### ISSUE TITLE
Feature Request: Script to feed MPN into Order of Service Markdown page

### ISSUE THREAD

**Issue by Talldad** [AshyPC/AshyPC.github.io#1]
1. Make a fixed heading "Ashburton Presbyterian Church"
2. Take Date of service from MPN heading & format with Title "Order of Service {date}"
3. Take each line of MPN Order of Service into an existing Markdown page
4. format line heading as bold
5. Apply line spacing of 2 or 3 to spread the layout across approx two-thirds of a portrait A4 page  
6. Finished page is rendered as part of AshyPC website for display/printing

Script could be based on mpnimport.pike from OHP-HTML

**Comment by Rosuav** [comment]
Implemented in OHP-HTML using existing (hand-made) content as a broad template.
