### ISSUE TITLE
Feature Request: Build Sermon Notes Markdown Page

### ISSUE THREAD

**Issue by Talldad** [AshyPC/AshyPC.github.io#2]
Similar to issue #1
1. Make a heading level 3 from "Sermon Outline: [preacher] {service date}" (MPN line will include preacher name)
2. Make a heading level 3 from Sermon Title & Passage line in MPN (use line as is)
3. For each line of the outline (Intro, points 1-n, Conclusion as nec)
3.1 divide available lines (33 to end of page) between each point (approx 7 lines each; reduce Intro and Conc if nec to fit all on one page)
3.2 set each line of text to Heading 4

NB: Github MD requires &NBSP & <BR> tags to force blank lines to be rendered. 
  
Script could be based on mpnimport.pike from OHP-HTML

**Comment by Rosuav** [comment]
Implemented in OHP-HTML using existing (hand-made) content as a broad template. GitHub markdown does NOT require anyone to force blank lines to be rendered, because we don't want blank lines - we want spacing. That's what style sheets are for.
